### ISSUE TITLE
Referance error

### ISSUE THREAD

**Issue by screenslaver4443** [goldentg/DOW#5]
Hi when I try to run the bot I get:

ReferenceError: e is not defined
    at C:\Users\200093\Documents\DOW2\DOW\index.js:70:72
    at Map.forEach (<anonymous>)
    at C:\Users\200093\Documents\DOW2\DOW\index.js:68:22
    at Map.forEach (<anonymous>)
    at Client.<anonymous> (C:\Users\200093\Documents\DOW2\DOW\index.js:67:19)
    at Client.emit (events.js:327:22)
    at WebSocketConnection.triggerReady (C:\Users\200093\Documents\DOW2\DOW\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (C:\Users\200093\Documents\DOW2\DOW\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (C:\Users\200093\Documents\DOW2\DOW\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (C:\Users\200093\Documents\DOW2\DOW\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)

**Comment by goldentg** [comment]
fixed bug with new update
